/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Lógica.GeneracionDatos;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author fambr
 */
public class FormularioSeleccion extends javax.swing.JFrame {

    static GeneracionDatos info = new GeneracionDatos();

    /**
     * Creates new form FormularioSeleccion
     */
    public FormularioSeleccion() {
        HashMap datos = new HashMap();
        info.llenarDatos(datos);
        info.imprimir(datos);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnClientesTotales = new javax.swing.JButton();
        btnClientesAtendidos = new javax.swing.JButton();
        btnClientesNoAtendidos = new javax.swing.JButton();
        btnTmpMax = new javax.swing.JButton();
        btnTmpProm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("PANADERÍA LUCHITO");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("¿Qué deseas ver sobre los clientes de hoy?");

        btnClientesTotales.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnClientesTotales.setText("Clientes Totales");
        btnClientesTotales.setToolTipText("");
        btnClientesTotales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesTotalesActionPerformed(evt);
            }
        });

        btnClientesAtendidos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnClientesAtendidos.setText("Clientes Atendidos");
        btnClientesAtendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesAtendidosActionPerformed(evt);
            }
        });

        btnClientesNoAtendidos.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnClientesNoAtendidos.setText("Clientes No Atendidos");
        btnClientesNoAtendidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesNoAtendidosActionPerformed(evt);
            }
        });

        btnTmpMax.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnTmpMax.setText("Tiempo Máximo de Espera");
        btnTmpMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTmpMaxActionPerformed(evt);
            }
        });

        btnTmpProm.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnTmpProm.setText("Tiempo Promedio de Espera");
        btnTmpProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTmpPromActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClientesNoAtendidos)
                                .addGap(18, 18, 18)
                                .addComponent(btnTmpMax))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClientesTotales)
                                .addGap(18, 18, 18)
                                .addComponent(btnClientesAtendidos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnTmpProm))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesTotales)
                    .addComponent(btnClientesAtendidos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClientesNoAtendidos)
                    .addComponent(btnTmpMax))
                .addGap(18, 18, 18)
                .addComponent(btnTmpProm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesTotalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesTotalesActionPerformed
        // TODO add your handling code here:
        String texto = "La totlidad de clientes hoy fue de " + info.clientesTotales;
        JOptionPane.showMessageDialog(null, texto, "CLIENTES TOTALES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnClientesTotalesActionPerformed

    private void btnClientesAtendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesAtendidosActionPerformed
        // TODO add your handling code here:
        String texto = "La totalidad de clientes atendidos hoy fue de " + info.clientesAtendidos;
        JOptionPane.showMessageDialog(null, texto, "CLIENTES ATENDIDOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnClientesAtendidosActionPerformed

    private void btnClientesNoAtendidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesNoAtendidosActionPerformed
        // TODO add your handling code here:
        String texto = "La totalidad de clientes no atendidos hoy fue de " + info.clientesNoAtendidos + " un " + info.porcentajeClientesNoAtendidos 
                + "% de los clientes";
        JOptionPane.showMessageDialog(null, texto, "CLIENTES NO ATENDIDOS", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnClientesNoAtendidosActionPerformed

    private void btnTmpMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTmpMaxActionPerformed
        // TODO add your handling code here:
        String texto = "El tiempo máxmo de espera de un cliente hoy fue de " + info.tiempoMaximo + " segundos";
        JOptionPane.showMessageDialog(null, texto, "TIEMPO MÁXMIO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTmpMaxActionPerformed

    private void btnTmpPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTmpPromActionPerformed
        // TODO add your handling code here:
        String texto = "Hoy el tiempo promedio de espera de los clientes fue de  " + info.promedio + " segundos";
        JOptionPane.showMessageDialog(null, texto, "TIEMPO PROMEDIO", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnTmpPromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioSeleccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioSeleccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientesAtendidos;
    private javax.swing.JButton btnClientesNoAtendidos;
    private javax.swing.JButton btnClientesTotales;
    private javax.swing.JButton btnTmpMax;
    private javax.swing.JButton btnTmpProm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
