
import java.util.ArrayList;
import java.util.Collections;
import java.util.NoSuchElementException;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fambr
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
        try {
            generarEstadisticas(Movies.sala1);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 1");
        }
        try {
            generarEstadisticas(Movies.sala2);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 2");
        }
        try {
            generarEstadisticas(Movies.sala3);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 3");
        }
        try {
            generarEstadisticas(Movies.sala4);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 4");
        }
        try {
            generarEstadisticas(Movies.sala5);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 5");
        }
        try {
            generarEstadisticas(Movies.sala6);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 6");
        }
        try {
            generarEstadisticas(Movies.sala7);
        } catch (NoSuchElementException e) {
            JOptionPane.showMessageDialog(null, "No se han registrado ventas en la sala 7");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sala1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sala2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sala3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        sala4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sala5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sala6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sala7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Estadisticas");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("La pelicula más vista de la sala 1 fue: ");

        sala1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala1.setText(".");
        sala1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("La pelicula más vista de la sala 2 fue: ");

        sala2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala2.setText(".");
        sala2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("La pelicula más vista de la sala 3 fue: ");

        sala3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala3.setText(".");
        sala3.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("La pelicula más vista de la sala 4 fue: ");

        sala4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala4.setText(".");
        sala4.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("La pelicula más vista de la sala 5 fue: ");

        sala5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala5.setText(".");
        sala5.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("La pelicula más vista de la sala 6 fue: ");

        sala6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala6.setText(".");
        sala6.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setText("La pelicula más vista de la sala 7 fue: ");

        sala7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        sala7.setText(".");
        sala7.setToolTipText("");

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(sala1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sala2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sala3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sala4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sala5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sala6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sala7)))
                .addContainerGap(234, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sala1))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sala2))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sala3))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sala4))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sala5))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sala6))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(sala7))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadisticas().setVisible(true);
            }
        });
    }

    public static void generarEstadisticas(ArrayList<String> sala) {
        ArrayList estadisticaSala = Validador.validar(sala);
        int mayorSala = (int) Collections.max(estadisticaSala);
        if (sala == Movies.sala1) {
            sala1.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        } else if (sala == Movies.sala2) {
            sala2.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        } else if (sala == Movies.sala3) {
            sala3.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        } else if (sala == Movies.sala4) {
            sala4.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        } else if (sala == Movies.sala5) {
            sala5.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        } else if (sala == Movies.sala6) {
            sala6.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        } else if (sala == Movies.sala7) {
            sala7.setText(sala.get(estadisticaSala.indexOf(mayorSala)));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private static javax.swing.JLabel sala1;
    private static javax.swing.JLabel sala2;
    private static javax.swing.JLabel sala3;
    private static javax.swing.JLabel sala4;
    private static javax.swing.JLabel sala5;
    private static javax.swing.JLabel sala6;
    private static javax.swing.JLabel sala7;
    // End of variables declaration//GEN-END:variables
}
