
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author fambr
 */
public class Movies extends javax.swing.JFrame {

    static ArrayList<String> sala1 = new ArrayList();
    static ArrayList<String> sala2 = new ArrayList();
    static ArrayList<String> sala3 = new ArrayList();
    static ArrayList<String> sala4 = new ArrayList();
    static ArrayList<String> sala5 = new ArrayList();
    static ArrayList<String> sala6 = new ArrayList();
    static ArrayList<String> sala7 = new ArrayList();

    /**
     * Creates new form Movies
     */
    public Movies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();

        jButton1.setText("Avatar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peliculas Disponibles");

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton2.setText("Avengers: Endgame");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton3.setText("Titanic");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton4.setText("Star Wars: Episode VII – The Force Awakens");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton5.setText("Avengers: Infinity War");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton6.setText("Spider-Man: No Way Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton7.setText("Jurassic World");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton8.setText("The Lion King");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton9.setText("Avengers");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton10.setText("Fast and Furious 7");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton11.setText("Top Gun: Maverick");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton12.setText("Frozen II");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton13.setText("Avengers: Age of Ultron");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton14.setText("Black Panther");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton15.setText("Harry Potter and the Deathly Hallows: Part II\n");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jButton16.setText("Avatar");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton7)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton14)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton12))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton13)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jButton8)))
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton15)
                    .addComponent(jButton10)
                    .addComponent(jButton7)
                    .addComponent(jButton14)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton3)
                    .addComponent(jButton11)
                    .addComponent(jButton16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton13)
                    .addComponent(jButton2)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        switch (Salas.flag) {
            case 1:
                sala1.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Harry Potter and The Deathly Hallows: Part II");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        switch (Salas.flag) {
            case 1:
                sala1.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Fast and Furious 7");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Jurassic Wolrd");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Black Panther");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Black Panther");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Black Panther");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Black Panther");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Black Panther");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Black Panther");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Black Panther");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Frozen II");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Frozen II");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Frozen II");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Frozen II");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Frozen II");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Frozen II");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Frozen II");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Star Wars: Episode VII – The Force Awakens");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Avengers: Infinity War");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Titanic");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Titanic");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Titanic");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Titanic");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Titanic");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Titanic");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Titanic");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Top Gun: Maverick");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Avatar");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Avatar");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Avatar");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Avatar");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Avatar");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Avatar");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Avatar");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Spider-Man: No Way Home");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Avengers: Age of Ultron");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Avengers: Endgame");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("Avengers");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("Avengers");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("Avengers");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("Avengers");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("Avengers");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("Avengers");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("Avengers");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
                switch (Salas.flag) {
            case 1:
                sala1.add("The Lion King");
                RegistrarVentas.ventas.put(1, sala1);
                this.setVisible(false);
                break;
            case 2:
                sala2.add("The Lion King");
                RegistrarVentas.ventas.put(2, sala2);
                this.setVisible(false);
                break;
            case 3:
                sala3.add("The Lion King");
                RegistrarVentas.ventas.put(3, sala3);
                this.setVisible(false);
                break;
            case 4:
                sala4.add("The Lion King");
                RegistrarVentas.ventas.put(4, sala4);
                this.setVisible(false);
                break;
            case 5:
                sala5.add("The Lion King");
                RegistrarVentas.ventas.put(5, sala5);
                this.setVisible(false);
                break;
            case 6:
                sala6.add("The Lion King");
                RegistrarVentas.ventas.put(6, sala6);
                this.setVisible(false);
                break;
            case 7:
                sala7.add("The Lion King");
                RegistrarVentas.ventas.put(7, sala7);
                this.setVisible(false);
                break;
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
