/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Logica.ListaCantantesFamosos;
import static Logica.ListaCantantesFamosos.listaCantantesFamosos;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author fambr
 */
public class Modificar extends javax.swing.JFrame {

    int posicion;
    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
        visibles(false);
        crearBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreAnterior = new javax.swing.JLabel();
        lblAnterior = new javax.swing.JLabel();
        lblNuevo = new javax.swing.JLabel();
        txtFldNuevo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombreAnterior.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNombreAnterior.setText("Nombre Anterior");
        lblNombreAnterior.setToolTipText("");

        lblAnterior.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblAnterior.setText("(Nombre anterior)");

        lblNuevo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblNuevo.setText("Nuevo Nombre");

        txtFldNuevo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtFldNuevo.setText("(Nombre Nuevo)");

        btnGuardar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lblTitulo.setText("CAMBIAR DE NOMBRE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreAnterior)
                            .addComponent(lblNuevo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFldNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnterior)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnGuardar)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAnterior)
                    .addComponent(lblAnterior))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNuevo)
                    .addComponent(txtFldNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        ListaCantantesFamosos.listaCantantesFamosos.get(posicion).setNombres(this.txtFldNuevo.getText());
        Principal inicio = new Principal();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }
    
    private void visibles(boolean tf){
        this.btnGuardar.setVisible(tf);
        this.lblAnterior.setVisible(tf);
        this.lblNombreAnterior.setVisible(tf);
        this.lblNuevo.setVisible(tf);
        this.txtFldNuevo.setVisible(tf);
    }
    
    private void crearBotones(){
        ArrayList<JButton> botones = new ArrayList<>();
        ActionListener ejecutar = new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                for (int i = 0; i < botones.size(); i++) {
                    botones.get(i).setVisible(false);
                    if (botones.get(i) == e.getSource()){
                        lblAnterior.setText(listaCantantesFamosos.get(i).getNombres());
                        posicion = i;
                    }
                }
                visibles(true);
            }
            
        };   
        
        for (int i = 0; i < ListaCantantesFamosos.listaCantantesFamosos.size(); i++) {
            JButton btn = new JButton();
            btn.setBounds(100, (50 + (i * 50)), 100, 30);
            btn.setFont(new Font("Century Gothic", 0, 14));
            btn.setText("" + ListaCantantesFamosos.listaCantantesFamosos.get(i).getNombres());
            btn.addActionListener(ejecutar);
            botones.add(btn);
            this.add(btn);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel lblAnterior;
    private javax.swing.JLabel lblNombreAnterior;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtFldNuevo;
    // End of variables declaration//GEN-END:variables
}
