/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import LOGICA.Usuario;

/**
 *
 * @author Practica
 */
public class Pregunta5 extends javax.swing.JFrame {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnGrpP1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        radBtnAbstract = new javax.swing.JRadioButton();
        radBtnImplements = new javax.swing.JRadioButton();
        radBtnExtends = new javax.swing.JRadioButton();
        radBtnInherit = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        btnPrvs = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(356, 254));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("<html><b>Pregunta 5.</b><p> Elige aquellas definiciones de código que tienen que ver con herencia:<html>");
        lblTitulo.setToolTipText("");

        btnGrpP1.add(radBtnAbstract);
        radBtnAbstract.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnAbstract.setText("abstract public class Gallina");
        radBtnAbstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnAbstractActionPerformed(evt);
            }
        });

        btnGrpP1.add(radBtnImplements);
        radBtnImplements.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnImplements.setText("public class Gallina implements Ave  ");

        btnGrpP1.add(radBtnExtends);
        radBtnExtends.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnExtends.setText("public class Gallina extends Ave  ");
        radBtnExtends.setToolTipText("");

        btnGrpP1.add(radBtnInherit);
        radBtnInherit.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnInherit.setText("public class Gallina inherit Perro  ");
        radBtnInherit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnInheritActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNext.setText("SIGUIENTE");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrvs.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnPrvs.setText("ANTERIOR");
        btnPrvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrvsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radBtnAbstract)
                            .addComponent(radBtnImplements))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radBtnInherit)
                            .addComponent(radBtnExtends)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(20, Short.MAX_VALUE)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)))
                .addContainerGap(1, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrvs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radBtnAbstract)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnImplements))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radBtnInherit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnExtends)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrvs))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        boolean rta = radBtnExtends.isSelected();
        if (rta){
            Usuario.rtas[4] = true;
        }
        Pregunta6 p6 = new Pregunta6();
        p6.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void radBtnAbstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnAbstractActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnAbstractActionPerformed

    private void radBtnInheritActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnInheritActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnInheritActionPerformed

    private void btnPrvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrvsActionPerformed
        // TODO add your handling code here:
        Pregunta4 p4 = new Pregunta4();
        p4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrvsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpP1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrvs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radBtnAbstract;
    private javax.swing.JRadioButton radBtnExtends;
    private javax.swing.JRadioButton radBtnImplements;
    private javax.swing.JRadioButton radBtnInherit;
    // End of variables declaration//GEN-END:variables
}
