/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import LOGICA.Usuario;

/**
 *
 * @author Practica
 */
public class Pregunta4 extends javax.swing.JFrame {

    /**
     * Creates new form Pregunta1
     */
    public Pregunta4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnGrpP1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        radBtnCrear = new javax.swing.JRadioButton();
        radBtnConectar = new javax.swing.JRadioButton();
        radBtnExtender = new javax.swing.JRadioButton();
        radBtnDuplicar = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        btnPrvs = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(356, 254));

        lblTitulo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("<html><b>Pregunta 4.</b><p> ¿Qué significa instanciar una clase?<html>");
        lblTitulo.setToolTipText("");

        btnGrpP1.add(radBtnCrear);
        radBtnCrear.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnCrear.setText("Crear un objeto a partir de una clase");
        radBtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnCrearActionPerformed(evt);
            }
        });

        btnGrpP1.add(radBtnConectar);
        radBtnConectar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnConectar.setText("Conectar 2 clases entre sí");

        btnGrpP1.add(radBtnExtender);
        radBtnExtender.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnExtender.setText("Extender su funcionalidad");
        radBtnExtender.setToolTipText("");

        btnGrpP1.add(radBtnDuplicar);
        radBtnDuplicar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        radBtnDuplicar.setText("Duplicar una Clase");

        btnNext.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnNext.setText("SIGUIENTE");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrvs.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnPrvs.setText("ANTERIOR");
        btnPrvs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrvsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnCrear)
                    .addComponent(radBtnConectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnDuplicar)
                    .addComponent(radBtnExtender))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrvs)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addGap(142, 142, 142))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radBtnCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnConectar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(radBtnDuplicar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radBtnExtender)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(btnPrvs))
                .addGap(31, 31, 31))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        boolean rta = radBtnCrear.isSelected();
        if (rta){
            Usuario.rtas[3] = true;
        }
        Pregunta5 p5 = new Pregunta5();
        p5.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

    private void radBtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnCrearActionPerformed

    private void btnPrvsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrvsActionPerformed
        // TODO add your handling code here:
        Pregunta3 p3 = new Pregunta3();
        p3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPrvsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pregunta4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pregunta4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGrpP1;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrvs;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton radBtnConectar;
    private javax.swing.JRadioButton radBtnCrear;
    private javax.swing.JRadioButton radBtnDuplicar;
    private javax.swing.JRadioButton radBtnExtender;
    // End of variables declaration//GEN-END:variables
}
